### PR TITLE
Allow different docker login methods (AWS ECR & native docker login)

### PR DESCRIPTION
**Pull request by radykal-com**
Added the possibility to either use AWS ECR login or native docker login prior to docker pull the image

Current changes set the required flag to use one of the methods and made the changes required to the template to use them.

Missing the integration into the pipeline. Where does the include statement of this new task make sense?
- in configure_cloudformation.yml before include create_launchconfiguration
- in create_launchconfiguration.yml before the "Render cloud-config" as it is just before this new feature is only used <--- This is where it better fits for me.

### CODE REVIEW

**Comment by fiunchinho** [comment]
Thank you for the contribution!
I would add the file in create_launchconfiguration.yml , as you mentioned.
What do you think about setting the fact called `wimpy_docker_login` to the whole command? I mean, building the full command inside `resolve_docker_login.yml` instead of setting True and then having an `IF` in the cloud_config.j2. How does that sound?

**Comment by radykal-com** [comment]
Sounds good, gonna make those changes then

Anyway a simple "if" will be required, because the whole login functionality is optional, if you are just pulling a public image you will not need any login at all

**Comment by ismferd** [comment]
Hi,

Make sense that @fiunchinho said, into cloud_config file I would put environment behavior or environment configuration, but not how my app must be work.
And put docker login in `resolve_docker_login.yml` sound good, maybe we will change the file name.

Thanks @radykal-com

**Review by fiunchinho — APPROVED** [review]

**Review by fiunchinho — APPROVED** [review]

**Comment by fiunchinho** [comment]
I'll merge it!

**Pull request merged**
